In [1]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [2]:
import numpy as np
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [3]:
import torch

# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [4]:
#Create a numpy array
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [5]:
#Create 2x2 torch tensor of 1's
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [6]:
#Create 2x2 PyTorch tensor of random numbers
torch.rand((2,2))

tensor([[0.5424, 0.2277],
        [0.6785, 0.2341]])

In [7]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [10]:
#Re create the same random values with seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [12]:
#Create an array of numpy and print the type of it
np_array = np.ones((2, 2))
print(np_array)
print(type(np_array))

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [13]:
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [14]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [15]:
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

In [16]:
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [17]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [18]:
# Element-wise addition
c = torch.add(a, b)
print(c)

tensor([[1., 1.],
        [1., 1.]])


In [20]:
# Element-wise substraction
d = a - b
print(d)

tensor([[1., 1.],
        [1., 1.]])


In [23]:
# Element-wise multiplication
e = a * b
print(e)

tensor([[0., 0.],
        [0., 0.]])


In [25]:
#Element wise division
f = b/a
print(f)

tensor([[0., 0.],
        [0., 0.]])


In [26]:
#Create a one dimensional torch tensor of length 10
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [27]:
#Get the mean for the first dimension
a.mean(dim=0)

tensor(5.5000)

In [29]:
#Create a two dimensional torch tensor of length 10
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
a.size()

torch.Size([2, 10])

In [30]:
#Get the mean of the first dimension
a.mean(dim=1)

tensor([5.5000, 5.5000])